### ISSUE TITLE
NTriples output

### ISSUE THREAD

**Issue by ktk** [OpenTransport/gtfs-csv2rdf#10]
It would be nice to have an option for NTriples output as well. Turtle is nicer to read but for bulk-loading & distribution NT is more practical IMHO.

**Comment by pietercolpaert** [comment]
I'll implement it later this month: minor changes are needed :)

**Comment by pietercolpaert** [comment]
As promised: a fix for this issue. Sorry it took so long :)

**Comment by ktk** [comment]
No worries, thanks for all work! Looks like all my issues are implemented/fixed now :+1: 

I will run it through the Swiss dataset later this year, I have some plans to make it somewhat stable available on an endpoint but this needs some additional funding/hardware first.
