### ISSUE TITLE
Do not use the name of the input file in the URIs (or make it optional)

### ISSUE THREAD

**Issue by ktk** [OpenTransport/gtfs-csv2rdf#12]
It seems that the name of the original input file is represented in the output URI. This is not really helpful from a persistence point of view as the input file does not have anything to do with it.

I get:

    <http://data.example.org/gtfs_complete/0.1/stops/8576432> a gtfs:Stop;

so `gtfs_complete` is the input file I used. Would be nice if this could be configured instead.

**Comment by pietercolpaert** [comment]
Good comment: the baseuri is now e.g., `http://data.example.org/gtfs_complete/0.1/`
