### ISSUE TITLE
Data type for arrivalTime and departureTime

### ISSUE THREAD

**Issue by ktk** [OpenTransport/gtfs-csv2rdf#13]
According to the GTFS specification `arrivalTime` and `departureTime` can have more than 24 hours to represent connections which are technically on a new day but before the end of the "daily" public transport schedule. As an example a bus departing at 01:33 would be listed as 25:33:00.

While this makes sense for what GTFS aims to do it's highly inconvenient for querying the data with SPARQL. When using SPARQL one wants to be able to use the `FILTER` keyword to restrict to time ranges for the particular query. This is in that form not possible as we cannot assign standard values like `xsd:time` to it.

In this issue I would like to collect ideas of how this could be solved. I have several ideas which I will add as comments, all of them need a discussion to see if they are feasible or not.

**Comment by pietercolpaert** [comment]
Good point!

We might in fact just add another predicate which tells how many days the trip is now running and use a regular dcterms:date instead.

I would propose:
 * To keep `gtfs:arrivalTime` and `gtfs:departureTime` into existence, just to be able to point to these semantics, but discouraging its use
 * To introduce a new property `gtfs:tripDay` which defaults to 0 and increases with the `Math.mod()` of the hour

**Comment by ktk** [comment]
I was having a discussion on the Jena list about this, there were two proposals which I will add as comments

**Comment by ktk** [comment]
Via James Anderson (not on mailing list)

> as the domain is not time of day, have you considered to use a duration instead?

> if one takes your description as it stands, you seek to represent a duration either from midnight or from beginning of service, or some other point in time which fits your model.
if you use a duration to model exactly that,  xsd:dayTimeDuration should have sufficient capacity and the time of day for a given event would be the combination of that duration and the start of the respective service day.

I replied that this makes sense and I need to see if this would work in filtering: 

> identity-based filtering should work for durations as well as any other datatype.
if you need other predicates, such as ‘<' or ‘>', or need to perform combinations, those will depend on your query processor's capabilities.
as the standard requires support for xsd:dateTime only (http://www.w3.org/TR/sparql11-query/#operandDataTypes), if yours supports xsd:time in addition, it may also support the concrete durations.

**Comment by ktk** [comment]
Via [Andy Seaborne](https://mail-archives.apache.org/mod_mbox/jena-users/201506.mbox/%3C557EF188.4040209@apache.org%3E)

>If you can translate to xsd date/time values, < and > will work.
>
>One approach is to add some custom functions that "casts" the different way of writing times into something that can be tested.
>
 > gtfsFn:timestamp("2015-06-15T25:33:00"^^:customDatatype)
>
>which returns  "2015-06-16T01:33:00"^^xsd:dateTime
>which is an RDF term that does mao into ARQ's date/time code.
>
>Another approach is like rules: to add properties: this is a post data-generation expansion (perl or etc will do it).
>
>:bus :departs "25:33:00"^^:customDatatype .
>
>and add
>
>:bus :departsXSD "01:33:00"^^xsd:time .
>
>
>So "before 09:00am" where 02:00:00 is the end of logical day.
>
>FILTER (?t > "02:00:00"^^xsd:time && ?t < "09:00:00"^^xsd:time)
>
>If "logical day" has overlaps, then it's all going to get a bit weird!
>
>And an off-the-wall solution: fake the timezone.  Move the bus times into +02:00.

**Comment by ktk** [comment]
Is there any definition in the GTFS spec on how long such a day can last or is this up to the provider to decide?

**Comment by pietercolpaert** [comment]
Up to the provider :-)

I personally like my first comment best as a solution: otherwise it looks like the start of a lot of workarounds...

**Comment by ktk** [comment]
Yeah that's fine with me, this is probably the only solution which will not require special functions on the SPARQL endpoint. If someone doesn't like this approach they can still implement another solution based on those proposals for example.

**Comment by pietercolpaert** [comment]
Now that I'm thinking further: duration seems like a good solution... What takes your preference?

**Comment by ktk** [comment]
I think with `xsd:dayTimeDuration` we would have a clear data type which matches the semantics of what GTFS wants to express so yes, I'm in.

We still might need to have an additional value to get compatible with SPARQL 1.1 compliant stores with no extensions for ` xsd:dayTimeDuration`.

I'm not sure if I can follow on your idea with `gtfs:tripDay`though.

**Comment by ktk** [comment]
I asked Andy about what ARQ/Fuseki supports in that regard, [interesting answer](https://mail-archives.apache.org/mod_mbox/jena-users/201506.mbox/%3c55871F4F.1000605@apache.org%3e):

> ARQ supports all the XSD atomic datatypes, including all the date/time/duration, but not all the XML related ones (so not sequences, xsd:NOTATION, XML-specific subtypes of xsd:string).
>
>Durations are helpful if you include the start point of the duration. Just giving a duration doesn't fix it on the timeline, so it might mean any day or time. Durations are not the most friendly of lexical forms however.
>
> But it is adding an extra property so a translated
> 
>     gtfs:arrivalTimeXSD

> which is a proper xsd:datetime for calculation (then considering the gtfs:arrivalTime as some presentation form akin to an rdfs:label) keeps you inside unrestricted SPARQL.  Well, for the limited xsd:dateTime support required for comparison, not:
>
>      xsd:dateTime - xsd:dateTime => xsd:duration
>
>and it strikes me that how long the journey takes is useful information.  That could be added as well (so not need to calculate in SPARQL) but waiting time between arriving on one bus and leaving on another is a calculation or N^2 triples.

**Comment by pietercolpaert** [comment]
Giving this some more thought, I'm going to stay as close as possible to the original semantics and implement the `xsd:duration` dataType :)
