### ISSUE TITLE
Add stop_id as literal

### ISSUE THREAD

**Issue by ktk** [OpenTransport/gtfs-csv2rdf#14]
According to the [GTFS spec](https://developers.google.com/transit/gtfs/reference#stops_fields) the field `stop_id` seems mandatory and I assume this is what is used for the stop URI right now.

This ID is probably very handy as the transport provider is using them internally as well for other data sets so it would be nice if the ID is exposed as a literal value as well so it can be used for easier interlinking to other data from the provider.

**Comment by pietercolpaert** [comment]
Best to use predicate `dcterms:identifier` for this. Good point!

**Comment by pietercolpaert** [comment]
Right now, it appears that I have chosen to map stop_code to dcterms:identifier. Maybe it makes more sense to have a separate property for the stop_code

**Comment by ktk** [comment]
I read what `stop_code` is about but I never saw such an identifier. As this seems to be transport related I would also support to have a new property for `stop_code` and use `dcterms:identifier` for `stop_id`
