### ISSUE TITLE
JSON-LD support

### ISSUE THREAD

**Issue by pietercolpaert** [OpenTransport/gtfs-csv2rdf#15]
JSON-LD documents can be directly ingested in e.g., MongoDB or other document stores. It's thus interesting to be able to cluster the triples together into an object, so that it can be ingested in such a store for querying purposes.

### Suggested solution

Triples about related things will be streamed out next to each other. This can be easily explained: a row from CSV generated triples with the same subject and these triples are emitted in 1 code block.

We should be able to pipe these triples to a document generation transformer. This Transform class should: 
 * emit an ` @context` 
 * pipe out a compacted json-ld document without `@context` element (the context is emitted separately)

**Comment by pietercolpaert** [comment]
@lanthaler, @msporny @elf-pavlik @rubenverborgh - I wonder how generalizable this "streaming JSON-LD" would be. Pouring this in a specification could maybe bridge the gap between the Linked Data community and the Document store community.

**Comment by elf-pavlik** [comment]
Good question! I must admit not having clear idea on how to do it :| Maybe @mcollina has some insights?

Maybe using [Flattened Document Form](http://www.w3.org/TR/json-ld/#flattened-document-form), and first sending `@context` and than one by one objects from `@graph` array would do?

**Comment by pietercolpaert** [comment]
@elf-pavlik Check the commit https://github.com/OpenTransport/gtfs-csv2rdf/commit/6b0b3137d07d1577ea85d1c31b07e36430b81598 - It's already implemented by indeed using a flattened form :)

**Comment by pietercolpaert** [comment]
I've formalized it over here: https://github.com/pietercolpaert/jsonld-stream/blob/master/README.md
