### ISSUE TITLE
Converting throws error

### ISSUE THREAD

**Issue by BonaBeavis** [OpenTransport/gtfs-csv2rdf#18]
Hi,

I am trying to convert this file: http://www.ttesercizio.it/opendata/google_transit_extraurbano_tte.zip

Following error is thrown:

```
Error: Invalid opening quote at line 310
```

**Comment by BonaBeavis** [comment]
Apparently quotes are not allowed inside of stop-names

**Comment by pietercolpaert** [comment]
Can  you confirm this issue is fixed merging your PR? I released a new NPM package!
