### ISSUE TITLE
Project not building with node v10.7.0 and npm v6.4.1 on MacOs X

### ISSUE THREAD

**Issue by kremio** [OpenTransport/gtfs-csv2rdf#20]
Hello,

I was trying to install the project with NPM, but the process failed due to errors building **contextify**.
I looked it up and the **contextify** package is obsolete as it has been integrated to node.js.

I ran ```npm outdated``` and managed to build the project by updating the following dependencies:
csv to 0.4.6
jsonld to 1.1.0
n3 to 0.4.5

I then ran gtfs-csv2rdf to convert a 66 MB GTFS zip file to turtle and it produced a 4.63 GB turtle file, so it seems to work.

Should I make a pull-request?

**Comment by pietercolpaert** [comment]
Yes please!

**Comment by pietercolpaert** [comment]
Is this issue fixed now? Released a new package!

**Comment by kremio** [comment]
As far as I can tell from running the code on my machine: yes, it is fixed!
