### ISSUE TITLE
Problem unzipping gtfs file on MacOS

### ISSUE THREAD

**Issue by mstn** [OpenTransport/gtfs-csv2rdf#7]
When running this command

     ./utils/gtfs-csv2rdf/gtfs-csv2rdf matera-gtfs.zip 0.1 http://data.gtfs.org/  > matera_gtfsintriples.ttl

I get this error.

Running "exec:mkRdf" (exec) task
>> draining gtfs/calendar.txt
>> 
>> events.js:72
>>         throw er; // Unhandled 'error' event
>>               ^
>> Error: invalid signature: 0x80014

From here http://stackoverflow.com/questions/25874750/ios-build-fails-with-invalid-signature-0x80014-while-unzipping-the-ios-device-b
it seems that unzip npm package has some issue under macos.

**Comment by pietercolpaert** [comment]
Is this fixed on Mac OS now? Can you test?

**Comment by pietercolpaert** [comment]
I'm closing this issue for now. To be reopened if the issue reappears.
