### ISSUE TITLE
gtfs-rdf2csv

### ISSUE THREAD

**Issue by elf-pavlik** [OpenTransport/gtfs-csv2rdf#8]
We consider using [LinkedGTFS](https://github.com/OpenTransport/linked-gtfs) as a way to store all the data internally in various pieces of code which we currently work on.
Do you have plans to support serializing LinkedGTFS data as GTFS CSV?

**Comment by pietercolpaert** [comment]
Not at this moment, but it shouldn't be too difficult to code that...

**Comment by pietercolpaert** [comment]
@elf-pavlik Did you end up using this ontology 3 years ago? In the meantime, the Linked Connections stack grew a lot -- https://linkedconnections.org.

**Comment by elf-pavlik** [comment]
I think we used it, but after first 2 hackathons no one else picked up the project.
Thanks for the pointer, I'll take another look at https://linkedconnections.org
