### ISSUE TITLE
Incorrect date types

### ISSUE THREAD

**Issue by ktk** [OpenTransport/gtfs-csv2rdf#9]
I've successfully transformed the complete Swiss public transport data set with your script, thanks for the work! On a  more or less recent box with fast SSD this takes about 3 hours to complete.

However `tdbloader` from Jena is not too happy with some of the date fields found in the data:
    
    dct:date "20150227"^^xsd:date.

Do you need to have the pointer to the converted data set? I'm usually using [Moment.js](http://momentjs.com/) to get rid of weird date formats.

**Comment by pietercolpaert** [comment]
It seems like the most simplest thing is to change the script and fix the data strings so Jena likes them, right? Possibly `-` is the only thing that would be needed?

We can add a check for the dates each time a date is found. E.G., in https://github.com/OpenTransport/gtfs-csv2rdf/blob/master/lib/CalendarDatesTransformer.js#L32

With Moment.js, do you mean you have a pull request for me?

**Comment by ktk** [comment]
Ok let me try it, shouldn't be a big deal. Yes Jena really expects a correct xsd:date data type which is `2007-01-01` for example.

**Comment by pietercolpaert** [comment]
I've just learned xsd:date is not implementing the full iso8601 spec: without dashes is indeed not valid xsd:date. Thanks for pointing this out :)

src: http://books.xmlschemata.org/relaxng/ch19-77041.html

**Comment by ktk** [comment]
Correct, that's actually quite annoying as there are many use cases where ISO8601 would be more useful.
